@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@json = application/json

GET http://{{host}}/api/cat HTTP/1.1

###

POST http://{{host}}/api/cat HTTP/1.1
content-type: {{json}}

{
    "name": "Cirmi",
    "breed": "Europian Shorthair"
}